### ISSUE TITLE
miss file

### ISSUE THREAD

**Issue by lfs119** [MoleculeAI/TAGMol#1]
Hi, I am very interested in your wonderful work.  But when i try to run ' train_diffusion.py ',   there is a  FileNotFoundError: './data'/crossdocked_v1.1_rmsd1.0_pocket10/index.pkl  and I can not find the ‘‘index.pkl’’ in URL ‘https://drive.google.com/drive/folders/1INaXCjVZCOQ_awNeGl5Xpsde_8JfnJiy?usp=drive_link’

**Comment by xzliu6** [comment]
I had the same problem. Has the issue been resolved?
