### ISSUE TITLE
logger.warning('Evaluation failed for %s' % f'{example_idx}_{sample_idx}')

### ISSUE THREAD

**Issue by lfs119** [MoleculeAI/TAGMol#2]
hi,  When I run ''python scripts/evaluate_diffusion.py {OUTPUT_DIR} --docking_mode vina_score --protein_root data/test_set
"   from  sampling results of "bash scripts/batch_sample_multi_guided_diffusion.sh configs/noise_guide_multi/sampling_guided_qed_0.33_sa_0.33_ba_0.34.yml qed_0.33_sa_0.33_ba_0.34". I found the log is almost 'Evaluation failed ***'

![image](https://github.com/user-attachments/assets/b937a319-88a2-4b23-b14f-79bb932b3e16)

**Comment by subhakd** [comment]
Hi @lfs119, this seems unusual. could you let us know the following:
1. are you using the checkpoints shared by us or did you train them yourself?
2. do you have the lmdb file and the test_set directory inside `data/`? both are required for inference.
3. what is the numpy version that has been installed? at times, an unsupported version gets installed as part of dependency of some library and breaks things.
4. have you made any changes to the config files?
5. any other info you would like to share?

**Comment by lfs119** [comment]
1.  Yes, I used the checkpoints shared in './log' 
2.  I download data from your shared url(https://drive.google.com/drive/folders/1INaXCjVZCOQ_awNeGl5Xpsde_8JfnJiy?usp=drive_link)
3. numpy == 1.24.4
4. I haven't made any changes to the config files

**Comment by lfs119** [comment]
![Uploading TAGMOL.png…]()

**Comment by lfs119** [comment]
sample.yml文件
  model:
    checkpoint: ./pretrained_models/pretrained_diffusion.pt
  
  guide_models:
    - name: qed
      checkpoint: ./logs/training_dock_guide_qed_2024_01_06__01_35_21/checkpoints/186000.pt
      weight: 0.33
      guide_kind: Kd
      gradient_scale_cord: 20
      gradient_scale_categ: 0.0 #1e-10
      clamp_pred_max: 1.0
    - name: sa
      checkpoint: ./logs/training_dock_guide_sa_2024_01_20__15_38_49/checkpoints/162000.pt
      weight: 0.33
      guide_kind: Kd
      gradient_scale_cord: 5
      gradient_scale_categ: 0.0 #1e-10
      clamp_pred_max: 1.0
    - name: binding_affinity
      checkpoint: ./logs/training_dock_guide_2023_12_17__06_23_35/checkpoints/184000.pt
      weight: 0.34
      guide_kind: Kd
      gradient_scale_cord: 2.0
      gradient_scale_categ: 0.0 #1e-10
  
  sample:
    seed: 2021
    num_samples: 100
    num_steps: 1000
    pos_only: False
    center_pos_mode: protein
    sample_num_atoms: prior

**Comment by lfs119** [comment]
I also  find a log.txt in 'TAGMol/experiments_multi/qed_0.33_sa_0.33_ba_0.34/eval_results/'  and  
[log.txt](https://github.com/user-attachments/files/16606771/log.txt)

**Comment by subhakd** [comment]
hi @lfs119, sorry for the delayed response.
i think the issue has got to do with the library versions in the python environment. as such, i am able to run the code after cloning this repo.
could you please see if downgrading numpy to 1.23.0 helps? if it works, we will make sure to add this explicitly in the README.
also, did you setup the environment using [install via conda and pip](/MoleculeAI/TAGMol/#install-via-conda-and-pip) method or did you use the [install with .yml file](/MoleculeAI/TAGMol/#alternatively-install-with-yml-file) one? could you try with the first one, if you have not?

**Comment by subhakd** [comment]
btw, there is no error when i evaluate for `docking_mode=none` (which doesn't perform docking) even with numpy==1.24.4. however, `docking_mode=vina_score` doesn't work with this numpy version.
please let us know if downgrading solves the problem for you as well.

**Comment by lfs119** [comment]
Thanks, I setup the environment using [install via conda and pip](https://github.com/MoleculeAI/TAGMol/#install-via-conda-and-pip) method. and can get similariy results in README.md

**Comment by subhakd** [comment]
thank you for letting us know. we have removed this method now.
